const buttonData=[{buttonId:"button-2",messageId:"message-2",timerId:"timer-2",links:["https://sillinesswoollen.com/y4gsdhs1?key=364bb8c942775bcd18321c760529b9bd","https://sillinesswoollen.com/dzuxwijy?key=d6a729b20e0b3c46d15e4478d0ee1d4b","https://sillinesswoollen.com/hqcy31erjz?key=cab5ae9f04479c27ecf27ed5f4a7496b","https://sillinesswoollen.com/mda3nbcax3?key=d0b8d02243b60d8fe5149eaa478213ef","https://sillinesswoollen.com/n5zeue1rt?key=4118d6de05154a8b409f693189aa5c8b"],maxClicks:5,downloadLink:"",}];function fetchDownloadLink(retryCount=0){const proxyUrl='https://api.allorigins.win/raw?url=';const targetUrl='https://www.techebyninja.xyz/2024/12/how-to-get-chatgpt-plus-premium-cookies.html';fetch(proxyUrl+encodeURIComponent(targetUrl)).then(response=>response.text()).then(html=>{const parser=new DOMParser();const doc=parser.parseFromString(html,'text/html');const downloadElement=doc.querySelector('a#download_link');if(downloadElement){buttonData[0].downloadLink=downloadElement.href}else{console.error("Download link not found.")}}).catch(error=>{console.error("Error fetching the download link:",error);if(retryCount<2){console.log("Retrying...");fetchDownloadLink(retryCount+1)}else{buttonData[0].downloadLink="error"}})}
buttonData.forEach((data,index)=>{const button=document.getElementById(data.buttonId);const message=document.getElementById(data.messageId);const timerDisplay=document.getElementById(data.timerId);let clickCount=0;let openedTabs=[];let timeElapsed=!1;button.addEventListener("click",()=>{if(clickCount<data.maxClicks){const newTab=window.open(data.links[clickCount],"_blank");openedTabs.push(newTab);const remainingClicks=data.maxClicks-clickCount-1;if(remainingClicks>0){button.innerHTML=`<i class="fas fa-play-circle"></i> ${remainingClicks} Clicks Left`}}
clickCount++;if(clickCount===data.maxClicks){button.innerHTML=`<i class="fas fa-thank-you"></i> Thank You`;button.disabled=!0;button.style.cursor="not-allowed";message.innerHTML="Link is getting ready. Please wait!";let timeLeft=60;const countdown=setInterval(()=>{if(timeLeft>0){timerDisplay.innerHTML=`Time left: ${timeLeft} seconds`;timeLeft--}else{clearInterval(countdown);timeElapsed=!0;if(data.downloadLink==="error"){message.innerHTML=`<div class="warning-box" role="alert" aria-live="assertive">
                            <i class="fas fa-exclamation-triangle"></i>
                            <p class="warning-text">The server is experiencing high traffic. Please refresh the page and try again after a few minutes.</p>
                        </div>`}else if(data.downloadLink){message.innerHTML=`File is Ready: <a id="download-link-${index}" href="${data.downloadLink}" target="_blank" aria-label="Download the file">Click to download <i class="fas fa-download"></i></a>`}else{message.innerHTML=`<div class="warning-box" role="alert" aria-live="assertive">
                            <i class="fas fa-exclamation-triangle"></i>
                            <p class="warning-text">Failed to fetch the download link. Please try again later.</p>
                        </div>`}
timerDisplay.innerHTML=''}},1000);fetchDownloadLink();const intervalCheck=setInterval(()=>{if(openedTabs.some(tab=>tab.closed)&&!timeElapsed){clearInterval(countdown);clearInterval(intervalCheck);button.disabled=!0;button.style.cursor="not-allowed";message.innerHTML=`
                        <div class="warning-box" role="alert" aria-live="assertive">
                            <i class="fas fa-exclamation-triangle"></i>
                            <p class="warning-text">Please do not close the Advertise tabs before 60 seconds. Refresh the page and try again.</p>
                        </div>`;timerDisplay.innerHTML=''}},500)}})});
